services:
  - type: web
    name: biosynergie
    env: python
    buildCommand: ""
    startCommand: |
      python manage.py collectstatic --noinput &&
      gunicorn capteurs_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: capteurs_site.settings
      - key: DATABASE_URL
        fromDatabase:
          name: biosynergie-db
          property: connectionString
databases:
  - name: biosynergie-db

