# Generated by Django 5.2 on 2025-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('pressure', models.FloatField()),
                ('sun_intensity', models.FloatField(blank=True, null=True)),
                ('methane_production', models.FloatField(blank=True, null=True)),
                ('solar_production', models.FloatField(blank=True, null=True)),
                ('algae_activity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
